### ISSUE TITLE
GitHub pages not publishing properly

### ISSUE THREAD

**Issue by TakesTheBiscuit** [ContainerSolutions/runbooks#101]
You have a GH action to publish a page.
It doesn't seem to be working correctly - there's no content on the url?

The latest GH action output says:

```
Created deployment for 11b32e3ee5e5c2f0a38526041530ef9e3f9289bf
{"page_url":"https://containersolutions.github.io/runbooks/","status_url":"https://api.github.com/repos/ContainerSolutions/runbooks/pages/deployment/status/11b32e3ee5e5c2f0a38526041530ef9e3f9289bf","preview_url":""}

```

Chasing the page url and the deployment status don't seem to reveal anything

**Comment by TakesTheBiscuit** [comment]
https://containersolutions.github.io/runbooks/

**Comment by robel-yemane** [comment]
Thanks for reporting that @TakesTheBiscuit, It's been fixed now.
