### ISSUE TITLE
'outOfPods'

### ISSUE THREAD

**Issue by ianmiell** [ContainerSolutions/runbooks#19]

**Comment by carvido1** [comment]
Interesting references for this pod state:

* [Considerations for large clusters ](https://kubernetes.io/docs/setup/best-practices/cluster-large/)
* [Medium blog post to change the pod limit per node](https://medium.com/@initcron/how-to-increase-the-number-of-pods-limit-per-kubernetes-node-877dcec5e4fa)

**Comment by carvido1** [comment]
I'm trying to reproduce this error locally using kind. 

```bash
kind create cluster
kubectl config use-context kind-kind
```

To check the current number of pods we can use:

```bash
kubectl get po -A --no-headers | wc -l                                                                                              
      9
```

Let's modify the [kubelet maxPods parameter to 10 pods](https://v1-25.docs.kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration), the default is 110 according to the KubeletConfiguration documentation.

```bash
docker exec kind-control-plane /bin/bash -c "echo 'maxPods: 10' >> /var/lib/kubelet/config.yaml && systemctl restart kubelet"
```

And then we can create a deployment and see what happens:

```bash
kubectl create deployment nginx --image=nginx --replicas=2
deployment.apps/nginx created
```

```text
kubectl get pods
NAME                    READY   STATUS    RESTARTS   AGE
nginx-76d6c9b8c-g9sbc   1/1     Running   0          29s
nginx-76d6c9b8c-wht8w   0/1     Pending   0          29s
```

One pod stays in pending. 

```text
kubectl describe pod nginx-76d6c9b8c-wht8w | grep -A 5 Events
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  102s  default-scheduler  0/1 nodes are available: 1 Too many pods. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```

**Comment by carvido1** [comment]
It seems that after changing the kube-controller-manager `cluster-cidr` configuration I've got the message OutOfPods.

```text
root@kind-control-plane:/# cat /etc/kubernetes/manifests/kube-controller-manager.yaml | grep cluster-cidr
    - --cluster-cidr=10.244.0.0/29
```

```text
kubectl get po           
NAME                     READY   STATUS      RESTARTS        AGE
nginx-6776bd87f7-4c2d8   0/1     OutOfpods   0               11m
nginx-76d6c9b8c-g9sbc    1/1     Running     1 (2m43s ago)   33m
nginx-76d6c9b8c-wht8w    0/1     Pending     0               33m
```

The message OutOfPods could be related with the Pod CIDR as well as networking limitations related to cloud providers.

**Comment by carvido1** [comment]
Apparently the error comes from the following kubelet file [predicate.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L131). If we follow de code, kubelet checks with [generalFilter function](https://github.com/kubernetes/kubernetes/blob/c8010537913422cc221cdd784936ff99817f621c/pkg/kubelet/lifecycle/predicate.go#L261-L289) if a pod is suitable for a node, when the pod does not fit this function return one or more reasons.

When there is more than one reason, [kubelet only returns the message for the first one](https://github.com/kubernetes/kubernetes/blob/c8010537913422cc221cdd784936ff99817f621c/pkg/kubelet/lifecycle/predicate.go#L123) to match a switch case in the following preference PredicateFailureError > InsufficientResourceError > Default.

This could be the case why  I can't see the OutOfPods error. I will have another try.

**Comment by carvido1** [comment]
When I did my first tests I was using the nodeSelector property instead of the nodeName to skip the kube-scheduler, this was a wrong approach. I'm going to try again with the nodeName property.

After testing with a deployment I've found that the ReplicaSet is trying to create pods all the time, so instead of the deployment I have used two different pods. To create the pods (at the stage where we have the kubelet configuration with  `maxPods: 10`) I have used the following:

```bash
kubectl run nginx1 --image=nginx --dry-run=client -o json | jq '.spec += {"nodeName": "kind-control-plane"}' | kubectl apply -f -
kubectl run nginx2 --image=nginx --dry-run=client -o json | jq '.spec += {"nodeName": "kind-control-plane"}' | kubectl apply -f -
```
After applying this we can see the message we are looking for:

```text
➜  ~ kubectl get pods
NAME     READY   STATUS      RESTARTS   AGE
nginx1   1/1     Running     0          102s
nginx2   0/1     OutOfpods   0          102s
➜  ~ kubectl describe pod nginx2 
Name:             nginx2
Namespace:        default
Priority:         0
Service Account:  default
Node:             kind-control-plane/
Start Time:       Wed, 25 Jan 2023 13:46:41 +0100
Labels:           run=nginx2
Annotations:      <none>
Status:           Failed
Reason:           OutOfpods
Message:          Pod Node didn't have enough resource: pods, requested: 1, used: 10, capacity: 10
IP:               
IPs:              <none>
Containers:
  nginx2:
    Image:        nginx
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zpmm6 (ro)
Volumes:
  kube-api-access-zpmm6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Warning  OutOfpods  108s  kubelet  Node didn't have enough resource: pods, requested: 1, used: 10, capacity: 10
```
