### ISSUE TITLE
Python module not found

### ISSUE THREAD

**Issue by MansM** [ContainerSolutions/runbooks#65]
Could also be: forgot to activate the virtual env

**Comment by ianmiell** [comment]
Working on this, cf: https://github.com/ContainerSolutions/runbooks/commit/bcc7470b227e0e93b16a38c476d80f2596df9390

**Comment by robel-yemane** [comment]
@ianmiell should this issue be closed then?

**Comment by ianmiell** [comment]
Yup, closing.
